### ISSUE TITLE
operator does not exist: qna_status_enum ~~ unknown

### ISSUE THREAD

**Issue by hero-ilati** [Arteha/admin-bro-typeorm#16]
Hello!
Filter doesn't work with enum field in list page.

this is error message.

```
QueryFailedError: operator does not exist: qna_status_enum ~~ unknown
    at new QueryFailedError (D:\Projects\backend\src\error\QueryFailedError.ts:9:9)
    at Query.callback (D:\Projects\backend\src\driver\postgres\PostgresQueryRunner.ts:178:30)
    at Query.handleError (D:\Projects\backend\node_modules\pg\lib\query.js:146:19)
    at Connection.connectedErrorMessageHandler (D:\Projects\backend\node_modules\pg\lib\client.js:236:17)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at Socket.<anonymous> (D:\Projects\backend\node_modules\pg\lib\connection.js:121:12)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
```

**Comment by hero-ilati** [comment]
admin bro typeorm official fixed it.
https://github.com/SoftwareBrothers/admin-bro-typeorm
