### ISSUE TITLE
Receiving property.type is not a function

### ISSUE THREAD

**Issue by lp-bayramali** [Arteha/admin-bro-typeorm#5]
Using express server. 

Received error stack: 
```
TypeError: property.type is not a function
    at ExtendedRecord.toJSON (C:\Users\HP\Documents\demo-app-api\node_modules\admin-bro-typeorm\src\ExtendedRecord.ts:79:43)
    at C:\Users\HP\Documents\demo-app-api\node_modules\admin-bro\lib\backend\controllers\api-controller.js:120:45
    at Array.map (<anonymous>)
    at ApiController.search (C:\Users\HP\Documents\demo-app-api\node_modules\admin-bro\lib\backend\controllers\api-controller.js:120:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at handler (C:\Users\HP\Documents\demo-app-api\node_modules\admin-bro-expressjs\plugin.js:56:22)
```

**Comment by Arteha** [comment]
Hello.
Could you give information from the list below:
1. `admin-bro` version
2. `admin-bro-expressjs` version
3. `admin-bro-typeorm` version
4. An example when it happens (models and the options passed to `admin-bro` enough i think)

**Comment by lp-bayramali** [comment]
Hi,

### Versions and env details: 

1. `admin-bro`: "^1.5.2"
2. `admin-bro-expressjs`: "^0.4.0"
3. `admin-bro-typeorm`: "^0.1.6-alpha.2"
4. `typeorm`: "^0.2.21",

Database is postgres. Database server version is Postgres 12

### AdminBroOptions:
 ```
   const app = express()
    const port = 3000


    const options: AdminBroOptions = {
        // databases: [connection],
        resources: [User, ProfilePreferences]
    }

```

### User entity
```
import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    Unique,
    CreateDateColumn,
    UpdateDateColumn,
    OneToMany,
    ManyToOne,
    OneToOne,
    JoinColumn,
    BaseEntity
} from "typeorm";
import { Length, IsNotEmpty } from "class-validator";
import * as bcrypt from "bcryptjs";
import {Exclude} from "class-transformer";
import { ResetPasswordToken } from "./ResetPasswordToken";
import { Role } from "./Role";
import { Post } from "./Post";
import { PostLikes } from "./PostLike";
import { PostComments } from "./PostComment";
import { PostReport } from "./PostReport";
import { ProfilePreferences } from "./ProfilePreferences";

@Entity()
@Unique(["username"])
export class User extends BaseEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({type: 'varchar'})
    @Length(4, 20)
    username: string;

    @Column({type: 'varchar'})
    @Length(2, 20)
    firstName: string;

    @Column({type: 'varchar'})
    @Length(2, 20)
    lastName: string;

    @Column({type: 'varchar'})
    @Length(2, 20)
    email: string;

    @Column({type: 'varchar'})
    @Length(4, 100)
    @Exclude()
    password: string;

    @OneToMany(type => ResetPasswordToken, token => token.user)
    resetPasswordTokens: ResetPasswordToken[];

    @OneToMany(type => Post, post => post.user)
    posts: Post[];

    @OneToMany(type => PostLikes, postLike => postLike.user)
    likes: PostLikes[];

    @OneToMany(type => PostComments, postComment => postComment.user)
    comments!: PostComments[];

    @OneToMany(type => PostReport, postReport => postReport.user)
    reports!: PostReport[];

    @OneToOne(type => ProfilePreferences, profilePreferences => profilePreferences.user, {cascade: true, onDelete: 'CASCADE'})
    @JoinColumn() // Adds foreign key profileSettingsId to User.
    profilePreferences!: ProfilePreferences;

    @Column()
    @CreateDateColumn()
    createdAt: Date;

    @Column()
    @UpdateDateColumn()
    updatedAt: Date;

    @ManyToOne(type => Role, role => role.users)
    role: Role;

    hashPassword() {
        this.password = bcrypt.hashSync(this.password, 8);
    }

    checkIfUnencryptedPasswordIsValid(unencryptedPassword: string) {
        return bcrypt.compareSync(unencryptedPassword, this.password);
    }
} 
```

### ProfilePreference Entity
```

import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    OneToOne,
    BaseEntity
} from "typeorm";
import { Length } from "class-validator";
import { User } from "./User";
import { ProfileDisplayAs, AvailableLanguages } from "../models/profile";

@Entity()
export class ProfilePreferences extends BaseEntity {

    constructor() {
        super();
        
        this.preferedLanguage = AvailableLanguages.ENGLISH;
        this.profileDisplayAs = ProfileDisplayAs.NAME_SURNAME;
        this.profilePictureUrl = "";
        this.enabledCategoryNotifications = [];
    }

    @PrimaryGeneratedColumn()
    id: number;

    @Column({type: 'varchar'})
    @Length(4, 20)
    preferedLanguage: AvailableLanguages;

    @Column("simple-json", { nullable: true })
    enabledCategoryNotifications: { id: number, name: string }[];

    @Column({type: 'varchar'})
    @Length(2, 256)
    profilePictureUrl: string;

    @Column({type: 'varchar'})
    @Length(2, 64)
    profileDisplayAs: ProfileDisplayAs;

    @OneToOne(type => User, user => user.profilePreferences)
    user!: User;
}
```

### Generated query and error message
```

Admin panel app listening on port 3000!
query: SELECT "ProfilePreferences"."id" AS "ProfilePreferences_id", "ProfilePreferences"."preferedLanguage" AS "ProfilePreferences_preferedLanguage", "ProfilePreferences"."enabledCategoryNotifications" AS "ProfilePreferences_enabledCategoryNotifications", "ProfilePreferences"."profilePictureUrl" AS "ProfilePreferences_profilePictureUrl", "ProfilePreferences"."profileDisplayAs" AS "ProfilePreferences_profileDisplayAs" FROM "profile_preferences" "ProfilePreferences" ORDER BY "ProfilePreferences"."id" ASC LIMIT 10
query: SELECT COUNT(DISTINCT("ProfilePreferences"."id")) as "cnt" FROM "profile_preferences" "ProfilePreferences"
TypeError: property.type is not a function
    at ExtendedRecord.toJSON (C:\Users\HP\Documents\gostivar-app-api\node_modules\admin-bro-typeorm\src\ExtendedRecord.ts:79:43)
    at C:\Users\HP\Documents\gostivar-app-api\node_modules\admin-bro\lib\backend\actions\list-action.js:92:44
    at Array.map (<anonymous>)
    at Object.handler (C:\Users\HP\Documents\gostivar-app-api\node_modules\admin-bro\lib\backend\actions\list-action.js:92:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ActionDecorator.handler (C:\Users\HP\Documents\gostivar-app-api\node_modules\admin-bro\lib\backend\decorators\action-decorator.js:66:15)      
    at handler (C:\Users\HP\Documents\gostivar-app-api\node_modules\admin-bro-expressjs\plugin.js:56:22)

```

### Some details and comments:

Issue is happening when I'm clicking to any Entity name on AdminBro sidenav. Items are not listing. Item count is always 0.

**Comment by lp-bayramali** [comment]
The same error is retrieving for any of entities
```

query: SELECT "User"."id" AS "User_id", "User"."username" AS "User_username", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User"."email" AS "User_email", "User"."password" AS "User_password", "User"."createdAt" AS "User_createdAt", "User"."updatedAt" AS "User_updatedAt", "User"."profilePreferencesId" AS "User_profilePreferencesId", "User"."roleId" AS "User_roleId" FROM "user" "User" ORDER BY "User"."email" ASC LIMIT 50
TypeError: property.type is not a function
    at ExtendedRecord.toJSON (C:\Users\HP\Documents\gostivar-app-api\node_modules\admin-bro-typeorm\src\ExtendedRecord.ts:79:43)
    at C:\Users\HP\Documents\gostivar-app-api\node_modules\admin-bro\lib\backend\controllers\api-controller.js:120:45
    at Array.map (<anonymous>)
    at ApiController.search (C:\Users\HP\Documents\gostivar-app-api\node_modules\admin-bro\lib\backend\controllers\api-controller.js:120:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at handler (C:\Users\HP\Documents\gostivar-app-api\node_modules\admin-bro-expressjs\plugin.js:56:22)
```

I did run the query manually on DB IDE and query returns the data without any problem. Generated query is okay

**Comment by Arteha** [comment]
Probably you forgot to register adapter before running `AdminBro` route.
try this:
```
import { Database, Resource } from "admin-bro-typeorm";
import AdminBro from 'admin-bro'

AdminBro.registerAdapter({ Database, Resource });
```

**Comment by lp-bayramali** [comment]
> Probably you forgot to register adapter before running `AdminBro` route.
> try this:
> 
> ```
> import { Database, Resource } from "admin-bro-typeorm";
> import AdminBro from 'admin-bro'
> 
> AdminBro.registerAdapter({ Database, Resource });
> ```

Nope, adapter is registered already.

Here is the starter method:

```
import { Database, Resource } from "admin-bro-typeorm";


createConnection().then(async connection => {
    const app = express()
    const port = 3000

    const options: AdminBroOptions = {
        // databases: [connection],
        resources: [User, ProfilePreferences, Category]
    }
    const adminBro = new AdminBro(options)
    const router = AdminBroExpress.buildRouter(adminBro)

    app.get('/', (req, res) => res.send('Hello World!'))
    app.use(adminBro.options.rootPath, router)

    app.listen(port, () => console.log(`Admin panel app listening on port ${port}!`))

}).catch(error => console.log(error));
```

**Comment by lp-bayramali** [comment]
After some debugging, for Entity properties like relations Property.type() is throwing an error.

I added this falsy check for property && property.type and I'm able to get record without any problem.

![image](https://user-images.githubusercontent.com/58950124/71426251-21ff6100-26a7-11ea-82e7-1320ce29ee56.png)

**Comment by Arteha** [comment]
Your idea doesn't solve the problem. Try to `console.log(property instanceof Property, property)` and lets see what is it.
```typescript
import { Database, Resource } from "admin-bro-typeorm";


createConnection().then(async connection => {
    const app = express()
    const port = 3000

    const options: AdminBroOptions = {
        // databases: [connection],
        resources: [User, ProfilePreferences, Category]
    }
    const adminBro = new AdminBro(options)
    const router = AdminBroExpress.buildRouter(adminBro)

    app.get('/', (req, res) => res.send('Hello World!'))
    app.use(adminBro.options.rootPath, router)

    app.listen(port, () => console.log(`Admin panel app listening on port ${port}!`))

}).catch(error => console.log(error));
```
Is it whole piece? You still missing line:
```typescript
AdminBro.registerAdapter({ Database, Resource });
```

**Comment by lp-bayramali** [comment]
Yes adapter is registered.
![image](https://user-images.githubusercontent.com/58950124/71441628-91566e80-2702-11ea-9c91-8eadfb5d1452.png)

**Comment by lp-bayramali** [comment]
This breaking issue still continues unfortunately

**Comment by Arteha** [comment]
Did you tried this?

> console.log(property instanceof Property, property)

**Comment by lp-bayramali** [comment]
Receiving undefined for Property. console.log fails

**Comment by Arteha** [comment]
import Property to this file.
```
const {Property} = require("./Property");
```
Then use.

**Comment by lp-bayramali** [comment]
I'm adding full console.log here:

[console.log(property instanceof Property, property)](https://pastebin.com/tiCzpLT1)

Last column which is printed successfully is `updateDate`, then it returns `TypeError: property.type is not a function`. After `updateDate` the next one is profilePreferences which is a relation, not a column

**Comment by Arteha** [comment]
Invite me as collaborator to your repo

**Comment by lp-bayramali** [comment]
Hi Arteha, I added you to the project as a collaborator.  You can find the admin bro integration on this branch:https://github.com/bayraak/gostivar-app-api/tree/feature/admin-bro-integration Also there is needed to create a new .env file in root directory of the project.I will send below the credentials of dev env. Please put this settings to your .env set-up. TYPEORM_CONNECTION = postgresTYPEORM_HOST = ec2-54-228-243-29.eu-west-1.compute.amazonaws.comTYPEORM_USERNAME = nicppxatnqkohgTYPEORM_PASSWORD = 25b1246fc53999afc9ca5c7f19000bf47f0d25808bd5c349f9a800ca71d12f08TYPEORM_DATABASE = d8g3tdol6204bTYPEORM_PORT = 5432TYPEORM_SYNCHRONIZE = trueTYPEORM_ENTITIES = src/entity/**/*.tsTYPEORM_MIGRATIONS = src/migration/**/*.tsTYPEORM_SUBSCRIBERS = src/subscriber/**/*.tsTYPEORM_ENTITIES_DIR = src/entityTYPEORM_MIGRATIONS_DIR = src/migrationTYPEORM_LOGGING = trueTYPEORM_DRIVER_EXTRA = {"ssl": true}DATABASE_URL = postgres://nicppxatnqkohg:25b1246fc53999afc9ca5c7f19000bf47f0d25808bd5c349f9a800ca71d12f08@ec2-54-228-243-29.eu-west-1.compute.amazonaws.com:5432/d8g3tdol6204bAWS_ACCESS_KEY = AKIAJ55IXBBICADIWXHAAWS_SECRET_KEY = Ppeg46uS9KBS22ChSD5EDgf6ZKhGSl4VnDGHoypjAWS_S3_BUCKET = gostivarapp-devAMQP_CONNECTION_URL = amqp://itkpgxvg:WnmuG9JJxzOqRHsbJc4c_hVkiz-0a9-F@hedgehog.rmq.cloudamqp.com/itkpgxvg  If you have additional questions please ask. Regards, Bayram  From: Artem ZabolotnyiSent: Saturday, December 28, 2019 17:35To: Arteha/admin-bro-typeormCc: lp-bayramali; AuthorSubject: Re: [Arteha/admin-bro-typeorm] Receiving property.type is not a function (#5) Invite me as collaborator to your repo—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lp-bayramali** [comment]
Hi I added you as a collaborator to the project. There is needed some env configurations and will send you the details as an email

**Comment by Arteha** [comment]
So?

**Comment by Arteha** [comment]
@lp-bayramali

**Comment by bayraak** [comment]
I added you as a colloborator as you said @Arteha . You can see and reproduce the error if you want

**Comment by Arteha** [comment]
Send me a link to your repo.

**Comment by lp-bayramali** [comment]
Here is it: [REPO LINK](https://github.com/bayraak/gostivar-app-api/tree/feature/admin-bro-integration)

Admin bro integration is on this branch: `feature/admin-bro-integration`
The link directly references to that branch. Read README file to run the project

**Comment by FBI23** [comment]
Also receiving the same error, only difference, I'm using Aurora MySQL.

**Comment by szalo13** [comment]
I also had the same problem - adding `if(property && typeof property.type === 'function')` instead of `if(property)` in 44 line of ExtendedRecord fixed the problem ;>

**Comment by szalo13** [comment]
I added bugfix to pull requests some time ago, any progress on it?

**Comment by Arteha** [comment]
@szalo13 Hello.
`property` must be an instance of Property class. So adding `...  && typeof property.type === 'function'` is a temp patch and doesn't fix problem. I need to find out what is it at all. I can't simulate the problem. Could you check is `property instanceof Property` and `property .constructor.name` ?

**Comment by Zhomart** [comment]
I've checked it locally. `n == "constructor"` and `typeof property == "object"`. `property.type` is `undefined`.

`property.constructor.name == "Function"`.

for other fields, e.g. `n == "lastName"`, `typeof property == "property"` and `property.constructor.name == "Property"`

**Comment by Catanix** [comment]
Got same problem, added:
`if (property && typeof property != 'function')`
and it started to work. Hope you will fix it soon.

**Comment by szalo13** [comment]
Hi,

So are You going to merge this fix? :)

**Comment by Arteha** [comment]
The problem is patched in v0.1.6-alpha.9
